/************************************************************************************************
* Name      : AccountHelper
* Purpose   : Helper class to Account Trigger
* TestClass : AccountHelperTest
* Author    : Bruna Girão
* Date      : 19-06-2023
***************************************************************************************************/
public with sharing class AccountHelper {
    
   
}