/************************************************************************************************
* Name      : OpenCageGeocoderService
* Purpose   : Class to get Location Info from OpenCageData API (https://opencagedata.com/api)
* TestClass : OpenCageGeocoderServiceTest
* Author    : Bruna Girão
* Date      : 30-06-2023
--------------------------------------------------------------------------------------------------
Date                Modified By             Description
--------------------------------------------------------------------------------------------------
30-06-2023          Bruna Girão             create class 
***************************************************************************************************/
public with sharing class OpenCageGeocoderService {

    public OpenCageGeocoderService () {}
}